title: go.ausm.org
description: AUSM Link Shortener This is a repository built upon hlaueriksson/jekyll-url-shortener ✂️🔗 This is a template repository for making URL Shorteners with Jekyll and GitHub Pages. Create short URLs that can be easily shared, tweeted, or emailed to friends. Fork this repo to get started.
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: AUSMinnesota/go.ausm.org
#original repository: hlaueriksson/jekyll-url-shortener
